### PR TITLE
Fix/add tcp port support

### LINKED ISSUE #37: Support multiaddrs with `tcp/port/{ws, wss}` as well
Same way that libp2p-webrtc-star received this fix https://github.com/libp2p/js-libp2p-webrtc-star/pull/130

### PR DESCRIPTION
**Pull request by pgte**
Fixes #37

### CODE REVIEW

**Comment by lgierth** [comment]
Thanks! Could you also update the readme? Need to kill those addresses before people start using them :P

I'm also thinking it's okay to completely remove the no-/tcp support here since there's no backwards-compat concerns as with the webrtc transport, but that's @diasdavid's call I guess :)

**Comment by diasdavid** [comment]
> I'm also thinking it's okay to completely remove the no-/tcp support here since there's no backwards-compat concerns as with the webrtc transport, but that's @diasdavid's call I guess :)

I would be fine with both but you do bring a good point and since we have the chance, let's do as @lgierth suggests.

**Comment by pgte** [comment]
@lgierth docs: done by d2037bc4cd4f98ebc1fe0eda3a2a63cd0aa12329.

deprecate no-tcp: I think [this line](https://github.com/libp2p/js-libp2p-websocket-star/pull/38/files#diff-2b4ca49d4bb0a774c4d4c1672d7aa781R16) enforces that.

**Comment by pgte** [comment]
Tests are failing because of this issue on aegis: https://github.com/ipfs/aegir/issues/177

**Comment by diasdavid** [comment]
Can we have that test skipped for now so that CI is green but with a comment above pointing to the issue reporting the problem? Thank you!

**Comment by diasdavid** [comment]
@pgte now it fails because of linting https://travis-ci.org/libp2p/js-libp2p-websocket-star/jobs/309424155#L2297

**Pull request merged**
